// =============================================
//  CHINESE LEARNING WEBAPP — VOCABULARY DATA
//  HSK 1 – HSK 5
//  Fields: char, pinyin, tone (1-4, 5=neutral),
//          meaning, pos (part of speech), example, exampleMeaning
// =============================================

const HSK_DATA = {

  1: [
    { char:"你好", pinyin:"nǐ hǎo",   tone:3, meaning:"Hello",           pos:"phrase",   example:"你好！很高兴认识你。", exampleMeaning:"Hello! Nice to meet you." },
    { char:"谢谢", pinyin:"xiè xie",  tone:4, meaning:"Thank you",       pos:"phrase",   example:"谢谢你的帮助。",       exampleMeaning:"Thank you for your help." },
    { char:"再见", pinyin:"zài jiàn", tone:4, meaning:"Goodbye",         pos:"phrase",   example:"明天见，再见！",        exampleMeaning:"See you tomorrow, goodbye!" },
    { char:"我",   pinyin:"wǒ",       tone:3, meaning:"I / me",          pos:"pronoun",  example:"我是学生。",           exampleMeaning:"I am a student." },
    { char:"你",   pinyin:"nǐ",       tone:3, meaning:"you",             pos:"pronoun",  example:"你叫什么名字？",       exampleMeaning:"What is your name?" },
    { char:"他",   pinyin:"tā",       tone:1, meaning:"he / him",        pos:"pronoun",  example:"他是我的朋友。",       exampleMeaning:"He is my friend." },
    { char:"她",   pinyin:"tā",       tone:1, meaning:"she / her",       pos:"pronoun",  example:"她很漂亮。",           exampleMeaning:"She is beautiful." },
    { char:"们",   pinyin:"men",      tone:5, meaning:"-s (plural)",     pos:"suffix",   example:"我们是朋友。",         exampleMeaning:"We are friends." },
    { char:"是",   pinyin:"shì",      tone:4, meaning:"to be (am/is/are)",pos:"verb",    example:"我是中国人。",         exampleMeaning:"I am Chinese." },
    { char:"有",   pinyin:"yǒu",      tone:3, meaning:"to have",         pos:"verb",     example:"我有一只猫。",         exampleMeaning:"I have a cat." },
    { char:"不",   pinyin:"bù",       tone:4, meaning:"not / no",        pos:"adverb",   example:"我不喜欢咖啡。",       exampleMeaning:"I don't like coffee." },
    { char:"好",   pinyin:"hǎo",      tone:3, meaning:"good",            pos:"adj",      example:"这个苹果很好吃。",     exampleMeaning:"This apple is delicious." },
    { char:"大",   pinyin:"dà",       tone:4, meaning:"big / large",     pos:"adj",      example:"这个房间很大。",       exampleMeaning:"This room is very big." },
    { char:"小",   pinyin:"xiǎo",     tone:3, meaning:"small / little",  pos:"adj",      example:"她的包很小。",         exampleMeaning:"Her bag is very small." },
    { char:"多",   pinyin:"duō",      tone:1, meaning:"many / much",     pos:"adj",      example:"这里有很多人。",       exampleMeaning:"There are many people here." },
    { char:"少",   pinyin:"shǎo",     tone:3, meaning:"few / little",    pos:"adj",      example:"钱太少了。",           exampleMeaning:"The money is too little." },
    { char:"人",   pinyin:"rén",      tone:2, meaning:"person / people",  pos:"noun",    example:"那个人是谁？",         exampleMeaning:"Who is that person?" },
    { char:"学生", pinyin:"xuéshēng", tone:2, meaning:"student",         pos:"noun",     example:"他是大学生。",         exampleMeaning:"He is a college student." },
    { char:"老师", pinyin:"lǎoshī",   tone:3, meaning:"teacher",         pos:"noun",     example:"我的老师很好。",       exampleMeaning:"My teacher is very good." },
    { char:"朋友", pinyin:"péngyou",  tone:2, meaning:"friend",          pos:"noun",     example:"她是我最好的朋友。",   exampleMeaning:"She is my best friend." },
    { char:"妈妈", pinyin:"māma",     tone:1, meaning:"mom / mother",    pos:"noun",     example:"妈妈在家吗？",         exampleMeaning:"Is mom at home?" },
    { char:"爸爸", pinyin:"bàba",     tone:4, meaning:"dad / father",    pos:"noun",     example:"爸爸去上班了。",       exampleMeaning:"Dad went to work." },
    { char:"家",   pinyin:"jiā",      tone:1, meaning:"home / family",   pos:"noun",     example:"我的家在北京。",       exampleMeaning:"My home is in Beijing." },
    { char:"中国", pinyin:"Zhōngguó", tone:1, meaning:"China",           pos:"noun",     example:"中国是一个大国。",     exampleMeaning:"China is a large country." },
    { char:"一",   pinyin:"yī",       tone:1, meaning:"one",             pos:"number",   example:"我有一个哥哥。",       exampleMeaning:"I have one older brother." },
    { char:"二",   pinyin:"èr",       tone:4, meaning:"two",             pos:"number",   example:"我住在二楼。",         exampleMeaning:"I live on the second floor." },
    { char:"三",   pinyin:"sān",      tone:1, meaning:"three",           pos:"number",   example:"我有三个朋友。",       exampleMeaning:"I have three friends." },
    { char:"四",   pinyin:"sì",       tone:4, meaning:"four",            pos:"number",   example:"他四岁了。",           exampleMeaning:"He is four years old." },
    { char:"五",   pinyin:"wǔ",       tone:3, meaning:"five",            pos:"number",   example:"苹果有五个。",         exampleMeaning:"There are five apples." },
    { char:"六",   pinyin:"liù",      tone:4, meaning:"six",             pos:"number",   example:"今天是六号。",         exampleMeaning:"Today is the 6th." },
    { char:"七",   pinyin:"qī",       tone:1, meaning:"seven",           pos:"number",   example:"七点起床。",           exampleMeaning:"Wake up at seven o'clock." },
    { char:"八",   pinyin:"bā",       tone:1, meaning:"eight",           pos:"number",   example:"八月很热。",           exampleMeaning:"August is very hot." },
    { char:"九",   pinyin:"jiǔ",      tone:3, meaning:"nine",            pos:"number",   example:"九月开学。",           exampleMeaning:"School starts in September." },
    { char:"十",   pinyin:"shí",      tone:2, meaning:"ten",             pos:"number",   example:"十个苹果。",           exampleMeaning:"Ten apples." },
    { char:"零",   pinyin:"líng",     tone:2, meaning:"zero",            pos:"number",   example:"今天零度。",           exampleMeaning:"It's zero degrees today." },
    { char:"今天", pinyin:"jīntiān",  tone:1, meaning:"today",           pos:"noun",     example:"今天天气不错。",       exampleMeaning:"The weather is nice today." },
    { char:"明天", pinyin:"míngtiān", tone:2, meaning:"tomorrow",        pos:"noun",     example:"明天我去北京。",       exampleMeaning:"I'm going to Beijing tomorrow." },
    { char:"昨天", pinyin:"zuótiān",  tone:2, meaning:"yesterday",       pos:"noun",     example:"昨天下雨了。",         exampleMeaning:"It rained yesterday." },
    { char:"年",   pinyin:"nián",     tone:2, meaning:"year",            pos:"noun",     example:"今年是2025年。",       exampleMeaning:"This year is 2025." },
    { char:"月",   pinyin:"yuè",      tone:4, meaning:"month / moon",    pos:"noun",     example:"这个月很忙。",         exampleMeaning:"This month is very busy." },
    { char:"日",   pinyin:"rì",       tone:4, meaning:"day / sun",       pos:"noun",     example:"今日天气晴。",         exampleMeaning:"Today's weather is sunny." },
    { char:"水",   pinyin:"shuǐ",     tone:3, meaning:"water",           pos:"noun",     example:"我想喝水。",           exampleMeaning:"I want to drink water." },
    { char:"饭",   pinyin:"fàn",      tone:4, meaning:"rice / meal",     pos:"noun",     example:"吃饭了吗？",           exampleMeaning:"Have you eaten?" },
    { char:"苹果", pinyin:"píngguǒ",  tone:2, meaning:"apple",           pos:"noun",     example:"我喜欢吃苹果。",       exampleMeaning:"I like eating apples." },
    { char:"猫",   pinyin:"māo",      tone:1, meaning:"cat",             pos:"noun",     example:"我家有一只猫。",       exampleMeaning:"I have a cat at home." },
    { char:"狗",   pinyin:"gǒu",      tone:3, meaning:"dog",             pos:"noun",     example:"这只狗很可爱。",       exampleMeaning:"This dog is very cute." },
    { char:"书",   pinyin:"shū",      tone:1, meaning:"book",            pos:"noun",     example:"我在看书。",           exampleMeaning:"I'm reading a book." },
    { char:"车",   pinyin:"chē",      tone:1, meaning:"car / vehicle",   pos:"noun",     example:"他开车上班。",         exampleMeaning:"He drives to work." },
    { char:"岁",   pinyin:"suì",      tone:4, meaning:"years old",       pos:"noun",     example:"我二十岁了。",         exampleMeaning:"I am twenty years old." },
    { char:"块",   pinyin:"kuài",     tone:4, meaning:"yuan / piece",    pos:"measure",  example:"这个苹果一块钱。",     exampleMeaning:"This apple costs one yuan." },
  ],

  2: [
    { char:"但是", pinyin:"dànshì",   tone:4, meaning:"but / however",   pos:"conj",     example:"我想去，但是没有时间。", exampleMeaning:"I want to go, but I have no time." },
    { char:"因为", pinyin:"yīnwèi",   tone:1, meaning:"because",         pos:"conj",     example:"因为下雨，我没去。",   exampleMeaning:"Because it rained, I didn't go." },
    { char:"所以", pinyin:"suǒyǐ",    tone:3, meaning:"so / therefore",  pos:"conj",     example:"很累，所以早睡了。",   exampleMeaning:"Very tired, so I slept early." },
    { char:"如果", pinyin:"rúguǒ",    tone:2, meaning:"if",              pos:"conj",     example:"如果你来，告诉我。",   exampleMeaning:"If you come, tell me." },
    { char:"虽然", pinyin:"suīrán",   tone:1, meaning:"although",        pos:"conj",     example:"虽然累，还是去了。",   exampleMeaning:"Although tired, I still went." },
    { char:"觉得", pinyin:"juéde",    tone:2, meaning:"to feel / think", pos:"verb",     example:"我觉得他很好。",       exampleMeaning:"I think he is very good." },
    { char:"喜欢", pinyin:"xǐhuān",   tone:3, meaning:"to like",         pos:"verb",     example:"我喜欢看电影。",       exampleMeaning:"I like watching movies." },
    { char:"知道", pinyin:"zhīdào",   tone:1, meaning:"to know",         pos:"verb",     example:"你知道他住哪里吗？",   exampleMeaning:"Do you know where he lives?" },
    { char:"想",   pinyin:"xiǎng",    tone:3, meaning:"to want / think", pos:"verb",     example:"我想去中国旅行。",     exampleMeaning:"I want to travel to China." },
    { char:"能",   pinyin:"néng",     tone:2, meaning:"can / be able to",pos:"verb",     example:"你能帮我吗？",         exampleMeaning:"Can you help me?" },
    { char:"可以", pinyin:"kěyǐ",     tone:3, meaning:"may / can",       pos:"verb",     example:"我可以进来吗？",       exampleMeaning:"May I come in?" },
    { char:"应该", pinyin:"yīnggāi",  tone:1, meaning:"should / ought to",pos:"verb",   example:"你应该多喝水。",       exampleMeaning:"You should drink more water." },
    { char:"超市", pinyin:"chāoshì",  tone:1, meaning:"supermarket",     pos:"noun",     example:"我去超市买东西。",     exampleMeaning:"I go to the supermarket to buy things." },
    { char:"医院", pinyin:"yīyuàn",   tone:1, meaning:"hospital",        pos:"noun",     example:"他在医院工作。",       exampleMeaning:"He works at the hospital." },
    { char:"学校", pinyin:"xuéxiào",  tone:2, meaning:"school",          pos:"noun",     example:"我去学校上课。",       exampleMeaning:"I go to school for class." },
    { char:"公司", pinyin:"gōngsī",   tone:1, meaning:"company",         pos:"noun",     example:"她在一家大公司工作。", exampleMeaning:"She works at a big company." },
    { char:"银行", pinyin:"yínháng",  tone:2, meaning:"bank",            pos:"noun",     example:"银行几点开门？",       exampleMeaning:"What time does the bank open?" },
    { char:"机场", pinyin:"jīchǎng",  tone:1, meaning:"airport",         pos:"noun",     example:"我去机场接朋友。",     exampleMeaning:"I'm picking up a friend at the airport." },
    { char:"地铁", pinyin:"dìtiě",    tone:4, meaning:"subway / metro",  pos:"noun",     example:"我坐地铁上班。",       exampleMeaning:"I take the subway to work." },
    { char:"飞机", pinyin:"fēijī",    tone:1, meaning:"airplane",        pos:"noun",     example:"飞机几点起飞？",       exampleMeaning:"What time does the plane take off?" },
    { char:"手机", pinyin:"shǒujī",   tone:3, meaning:"mobile phone",    pos:"noun",     example:"我的手机没电了。",     exampleMeaning:"My phone has run out of battery." },
    { char:"电脑", pinyin:"diànnǎo",  tone:4, meaning:"computer",        pos:"noun",     example:"我用电脑工作。",       exampleMeaning:"I work on a computer." },
    { char:"问题", pinyin:"wèntí",    tone:4, meaning:"question / problem",pos:"noun",   example:"你有什么问题吗？",     exampleMeaning:"Do you have any questions?" },
    { char:"时间", pinyin:"shíjiān",  tone:2, meaning:"time",            pos:"noun",     example:"我没有时间。",         exampleMeaning:"I don't have time." },
    { char:"地方", pinyin:"dìfāng",   tone:4, meaning:"place",           pos:"noun",     example:"这个地方很漂亮。",     exampleMeaning:"This place is very beautiful." },
    { char:"事情", pinyin:"shìqing",  tone:4, meaning:"thing / matter",  pos:"noun",     example:"什么事情？",           exampleMeaning:"What's the matter?" },
    { char:"钱",   pinyin:"qián",     tone:2, meaning:"money",           pos:"noun",     example:"我没带钱。",           exampleMeaning:"I didn't bring money." },
    { char:"天气", pinyin:"tiānqì",   tone:1, meaning:"weather",         pos:"noun",     example:"今天天气怎么样？",     exampleMeaning:"What's the weather like today?" },
    { char:"颜色", pinyin:"yánsè",    tone:2, meaning:"color",           pos:"noun",     example:"你喜欢什么颜色？",     exampleMeaning:"What color do you like?" },
    { char:"电影", pinyin:"diànyǐng", tone:4, meaning:"movie / film",    pos:"noun",     example:"我们去看电影吧。",     exampleMeaning:"Let's go watch a movie." },
    { char:"音乐", pinyin:"yīnyuè",   tone:1, meaning:"music",           pos:"noun",     example:"我喜欢听音乐。",       exampleMeaning:"I like listening to music." },
    { char:"运动", pinyin:"yùndòng",  tone:4, meaning:"sport / exercise",pos:"noun",     example:"运动对身体好。",       exampleMeaning:"Exercise is good for the body." },
    { char:"旅游", pinyin:"lǚyóu",    tone:3, meaning:"travel / tourism",pos:"verb",     example:"我们去旅游吧！",       exampleMeaning:"Let's go travel!" },
    { char:"休息", pinyin:"xiūxi",    tone:1, meaning:"to rest",         pos:"verb",     example:"好好休息一下。",       exampleMeaning:"Rest well." },
    { char:"帮助", pinyin:"bāngzhù",  tone:1, meaning:"to help",         pos:"verb",     example:"谢谢你的帮助。",       exampleMeaning:"Thank you for your help." },
    { char:"告诉", pinyin:"gàosu",    tone:4, meaning:"to tell",         pos:"verb",     example:"告诉我你的名字。",     exampleMeaning:"Tell me your name." },
    { char:"快",   pinyin:"kuài",     tone:4, meaning:"fast / quick",    pos:"adj",      example:"他走得很快。",         exampleMeaning:"He walks very fast." },
    { char:"慢",   pinyin:"màn",      tone:4, meaning:"slow",            pos:"adj",      example:"请说慢一点。",         exampleMeaning:"Please speak more slowly." },
    { char:"热",   pinyin:"rè",       tone:4, meaning:"hot",             pos:"adj",      example:"今天很热。",           exampleMeaning:"It's very hot today." },
    { char:"冷",   pinyin:"lěng",     tone:3, meaning:"cold",            pos:"adj",      example:"冬天很冷。",           exampleMeaning:"Winter is very cold." },
    { char:"贵",   pinyin:"guì",      tone:4, meaning:"expensive",       pos:"adj",      example:"这个太贵了。",         exampleMeaning:"This is too expensive." },
    { char:"便宜", pinyin:"piányí",   tone:2, meaning:"cheap / inexpensive",pos:"adj",   example:"这件衣服很便宜。",     exampleMeaning:"This piece of clothing is very cheap." },
    { char:"漂亮", pinyin:"piàoliang",tone:4, meaning:"beautiful / pretty",pos:"adj",    example:"她很漂亮。",           exampleMeaning:"She is very beautiful." },
    { char:"干净", pinyin:"gānjìng",  tone:1, meaning:"clean",           pos:"adj",      example:"房间很干净。",         exampleMeaning:"The room is very clean." },
    { char:"聪明", pinyin:"cōngmíng", tone:1, meaning:"smart / clever",  pos:"adj",      example:"他的孩子很聪明。",     exampleMeaning:"His child is very smart." },
  ],

  3: [
    { char:"经验", pinyin:"jīngyàn",  tone:1, meaning:"experience",      pos:"noun",     example:"他有丰富的工作经验。", exampleMeaning:"He has rich work experience." },
    { char:"文化", pinyin:"wénhuà",   tone:2, meaning:"culture",         pos:"noun",     example:"中国文化博大精深。",   exampleMeaning:"Chinese culture is profound." },
    { char:"历史", pinyin:"lìshǐ",    tone:4, meaning:"history",         pos:"noun",     example:"中国有几千年历史。",   exampleMeaning:"China has thousands of years of history." },
    { char:"环境", pinyin:"huánjìng", tone:2, meaning:"environment",     pos:"noun",     example:"我们要保护环境。",     exampleMeaning:"We must protect the environment." },
    { char:"机会", pinyin:"jīhuì",    tone:1, meaning:"opportunity / chance",pos:"noun", example:"这是个好机会。",       exampleMeaning:"This is a good opportunity." },
    { char:"关系", pinyin:"guānxi",   tone:1, meaning:"relationship",    pos:"noun",     example:"我们关系很好。",       exampleMeaning:"We have a good relationship." },
    { char:"方法", pinyin:"fāngfǎ",   tone:1, meaning:"method / way",    pos:"noun",     example:"你有什么好方法？",     exampleMeaning:"Do you have any good methods?" },
    { char:"生活", pinyin:"shēnghuó", tone:1, meaning:"life / to live",  pos:"noun",     example:"他的生活很幸福。",     exampleMeaning:"His life is very happy." },
    { char:"工作", pinyin:"gōngzuò",  tone:1, meaning:"work / job",      pos:"noun",     example:"她喜欢她的工作。",     exampleMeaning:"She likes her job." },
    { char:"情况", pinyin:"qíngkuàng",tone:2, meaning:"situation / condition",pos:"noun",example:"情况怎么样了？",       exampleMeaning:"How is the situation?" },
    { char:"交通", pinyin:"jiāotōng", tone:1, meaning:"traffic / transportation",pos:"noun",example:"这里交通很方便。",  exampleMeaning:"Transportation here is very convenient." },
    { char:"城市", pinixin:"chéngshì",tone:2, meaning:"city",            pos:"noun",     example:"上海是个大城市。",     exampleMeaning:"Shanghai is a big city." },
    { char:"国家", pinyin:"guójiā",   tone:2, meaning:"country / nation",pos:"noun",     example:"你是哪个国家的人？",   exampleMeaning:"What country are you from?" },
    { char:"问题", pinyin:"wèntí",    tone:4, meaning:"problem / question",pos:"noun",   example:"这个问题很难。",       exampleMeaning:"This problem is very difficult." },
    { char:"消息", pinyin:"xiāoxi",   tone:1, meaning:"news / message",  pos:"noun",     example:"你有什么新消息？",     exampleMeaning:"Do you have any news?" },
    { char:"压力", pinyin:"yālì",     tone:1, meaning:"pressure / stress",pos:"noun",    example:"他工作压力很大。",     exampleMeaning:"He has a lot of work pressure." },
    { char:"热情", pinyin:"rèqíng",   tone:4, meaning:"enthusiasm / warm",pos:"adj",     example:"她对工作很热情。",     exampleMeaning:"She is very enthusiastic about work." },
    { char:"认真", pinyin:"rènzhēn",  tone:4, meaning:"serious / earnest",pos:"adj",     example:"他学习很认真。",       exampleMeaning:"He studies very earnestly." },
    { char:"复杂", pinyin:"fùzá",     tone:4, meaning:"complicated",     pos:"adj",      example:"这件事很复杂。",       exampleMeaning:"This matter is very complicated." },
    { char:"简单", pinyin:"jiǎndān",  tone:3, meaning:"simple / easy",   pos:"adj",      example:"这道题很简单。",       exampleMeaning:"This question is very simple." },
    { char:"安全", pinyin:"ānquán",   tone:1, meaning:"safe / security", pos:"adj",      example:"这里很安全。",         exampleMeaning:"It is very safe here." },
    { char:"危险", pinyin:"wéixiǎn",  tone:2, meaning:"dangerous",       pos:"adj",      example:"这条路很危险。",       exampleMeaning:"This road is very dangerous." },
    { char:"重要", pinyin:"zhòngyào", tone:4, meaning:"important",       pos:"adj",      example:"这件事很重要。",       exampleMeaning:"This matter is very important." },
    { char:"特别", pinyin:"tèbié",    tone:4, meaning:"special / especially",pos:"adj",  example:"今天特别冷。",         exampleMeaning:"Today is especially cold." },
    { char:"常常", pinyin:"chángcháng",tone:2,meaning:"often / frequently",pos:"adverb", example:"我常常去图书馆。",     exampleMeaning:"I often go to the library." },
    { char:"已经", pinyin:"yǐjīng",   tone:3, meaning:"already",         pos:"adverb",   example:"他已经走了。",         exampleMeaning:"He has already left." },
    { char:"继续", pinyin:"jìxù",     tone:4, meaning:"to continue",     pos:"verb",     example:"请继续说。",           exampleMeaning:"Please continue." },
    { char:"解决", pinyin:"jiějué",   tone:3, meaning:"to solve / resolve",pos:"verb",   example:"我们要解决这个问题。", exampleMeaning:"We need to solve this problem." },
    { char:"发展", pinyin:"fāzhǎn",   tone:1, meaning:"to develop",      pos:"verb",     example:"科技快速发展。",       exampleMeaning:"Technology develops rapidly." },
    { char:"影响", pinyin:"yǐngxiǎng",tone:3, meaning:"to influence",    pos:"verb",     example:"天气影响心情。",       exampleMeaning:"Weather influences mood." },
    { char:"参加", pinyin:"cānjiā",   tone:1, meaning:"to participate",  pos:"verb",     example:"你参加比赛了吗？",     exampleMeaning:"Did you participate in the competition?" },
    { char:"选择", pinyin:"xuǎnzé",   tone:3, meaning:"to choose",       pos:"verb",     example:"你要怎么选择？",       exampleMeaning:"How will you choose?" },
    { char:"完成", pinyin:"wánchéng", tone:2, meaning:"to complete",     pos:"verb",     example:"任务已经完成了。",     exampleMeaning:"The task has been completed." },
    { char:"提高", pinyin:"tígāo",    tone:2, meaning:"to improve / raise",pos:"verb",   example:"我想提高我的汉语。",   exampleMeaning:"I want to improve my Chinese." },
    { char:"了解", pinyin:"liǎojiě",  tone:3, meaning:"to understand",   pos:"verb",     example:"我了解他的情况。",     exampleMeaning:"I understand his situation." },
  ],

  4: [
    { char:"经济", pinyin:"jīngjì",   tone:1, meaning:"economy / economics",pos:"noun",  example:"中国经济增长很快。",   exampleMeaning:"China's economy grows fast." },
    { char:"政治", pinyin:"zhèngzhì", tone:4, meaning:"politics",        pos:"noun",     example:"他对政治感兴趣。",     exampleMeaning:"He is interested in politics." },
    { char:"社会", pinyin:"shèhuì",   tone:4, meaning:"society",         pos:"noun",     example:"社会发展很快。",       exampleMeaning:"Society is developing rapidly." },
    { char:"科技", pinyin:"kējì",     tone:1, meaning:"science & technology",pos:"noun", example:"科技改变了我们的生活。",exampleMeaning:"Technology has changed our lives." },
    { char:"信息", pinyin:"xìnxī",    tone:4, meaning:"information",     pos:"noun",     example:"我需要更多信息。",     exampleMeaning:"I need more information." },
    { char:"观点", pinyin:"guāndiǎn", tone:1, meaning:"viewpoint / opinion",pos:"noun",  example:"请说说你的观点。",     exampleMeaning:"Please share your viewpoint." },
    { char:"态度", pinyin:"tàidu",    tone:4, meaning:"attitude",        pos:"noun",     example:"他的态度很好。",       exampleMeaning:"His attitude is very good." },
    { char:"目的", pinyin:"mùdì",     tone:4, meaning:"purpose / goal",  pos:"noun",     example:"你的目的是什么？",     exampleMeaning:"What is your purpose?" },
    { char:"结果", pinyin:"jiéguǒ",   tone:2, meaning:"result / outcome",pos:"noun",     example:"结果出来了吗？",       exampleMeaning:"Has the result come out?" },
    { char:"阶段", pinyin:"jiēduàn",  tone:1, meaning:"stage / phase",   pos:"noun",     example:"现在是重要阶段。",     exampleMeaning:"Now is an important stage." },
    { char:"制度", pinyin:"zhìdù",    tone:4, meaning:"system / institution",pos:"noun", example:"公司制度很严格。",     exampleMeaning:"The company's rules are very strict." },
    { char:"进步", pinyin:"jìnbù",    tone:4, meaning:"progress",        pos:"noun",     example:"你的汉语有很大进步。",  exampleMeaning:"Your Chinese has improved a lot." },
    { char:"矛盾", pinyin:"máodùn",   tone:2, meaning:"contradiction / conflict",pos:"noun",example:"两人之间有矛盾。", exampleMeaning:"There is a conflict between them." },
    { char:"责任", pinyin:"zérèn",    tone:2, meaning:"responsibility",  pos:"noun",     example:"这是你的责任。",       exampleMeaning:"This is your responsibility." },
    { char:"原因", pinyin:"yuányīn",  tone:2, meaning:"reason / cause",  pos:"noun",     example:"这件事的原因是什么？", exampleMeaning:"What is the reason for this?" },
    { char:"意义", pinyin:"yìyì",     tone:4, meaning:"meaning / significance",pos:"noun",example:"这很有意义。",       exampleMeaning:"This is very meaningful." },
    { char:"优势", pinyin:"yōushì",   tone:1, meaning:"advantage",       pos:"noun",     example:"我们有技术优势。",     exampleMeaning:"We have a technical advantage." },
    { char:"困难", pinyin:"kùnnan",   tone:4, meaning:"difficulty",      pos:"noun",     example:"遇到困难不要放弃。",   exampleMeaning:"Don't give up when you meet difficulties." },
    { char:"消费", pinyin:"xiāofèi",  tone:1, meaning:"consumption / spending",pos:"verb",example:"年轻人消费能力强。",  exampleMeaning:"Young people have strong spending power." },
    { char:"竞争", pinyin:"jìngzhēng",tone:4, meaning:"competition",     pos:"verb",     example:"市场竞争很激烈。",     exampleMeaning:"Market competition is very fierce." },
    { char:"合作", pinyin:"hézuò",    tone:2, meaning:"cooperation",     pos:"verb",     example:"我们需要相互合作。",   exampleMeaning:"We need to cooperate with each other." },
    { char:"调查", pinyin:"diàochá",  tone:4, meaning:"to investigate / survey",pos:"verb",example:"我们做了一个调查。", exampleMeaning:"We conducted a survey." },
    { char:"证明", pinyin:"zhèngmíng",tone:4, meaning:"to prove",        pos:"verb",     example:"你能证明你的观点吗？", exampleMeaning:"Can you prove your point?" },
    { char:"沟通", pinyin:"gōutōng",  tone:1, meaning:"to communicate",  pos:"verb",     example:"有效沟通非常重要。",   exampleMeaning:"Effective communication is very important." },
    { char:"实现", pinyin:"shíxiàn",  tone:2, meaning:"to realize/achieve",pos:"verb",   example:"梦想终于实现了。",     exampleMeaning:"The dream has finally been realized." },
    { char:"坚持", pinyin:"jiānchí",  tone:1, meaning:"to persist / insist",pos:"verb",  example:"坚持就是胜利。",       exampleMeaning:"Persistence means victory." },
    { char:"适应", pinyin:"shìyìng",  tone:4, meaning:"to adapt",        pos:"verb",     example:"他很快适应了新环境。", exampleMeaning:"He quickly adapted to the new environment." },
    { char:"忽视", pinyin:"hūshì",    tone:1, meaning:"to neglect / ignore",pos:"verb",  example:"不能忽视这个问题。",   exampleMeaning:"We cannot ignore this problem." },
    { char:"鼓励", pinyin:"gǔlì",     tone:3, meaning:"to encourage",    pos:"verb",     example:"老师鼓励学生多读书。", exampleMeaning:"The teacher encourages students to read more." },
    { char:"批评", pinyin:"pīpíng",   tone:1, meaning:"to criticize",    pos:"verb",     example:"老师批评了他。",       exampleMeaning:"The teacher criticized him." },
  ],

  5: [
    { char:"哲学", pinyin:"zhéxué",    tone:2, meaning:"philosophy",      pos:"noun",    example:"他学的是哲学。",       exampleMeaning:"He studies philosophy." },
    { char:"心理", pinyin:"xīnlǐ",    tone:1, meaning:"psychology / mentality",pos:"noun",example:"心理健康很重要。",   exampleMeaning:"Mental health is very important." },
    { char:"逻辑", pinyin:"luójí",     tone:2, meaning:"logic",           pos:"noun",    example:"你的逻辑不对。",       exampleMeaning:"Your logic is wrong." },
    { char:"辩证", pinyin:"biànzhèng", tone:4, meaning:"dialectical",     pos:"adj",     example:"要辩证地看问题。",     exampleMeaning:"We must look at problems dialectically." },
    { char:"价值观",pinyin:"jiàzhíguān",tone:4,meaning:"values",          pos:"noun",    example:"价值观影响行为。",     exampleMeaning:"Values influence behavior." },
    { char:"理念", pinyin:"lǐniàn",    tone:3, meaning:"concept / idea",  pos:"noun",    example:"企业理念很重要。",     exampleMeaning:"Corporate concepts are important." },
    { char:"抽象", pinyin:"chōuxiàng", tone:1, meaning:"abstract",        pos:"adj",     example:"这个概念很抽象。",     exampleMeaning:"This concept is very abstract." },
    { char:"本质", pinyin:"běnzhì",    tone:3, meaning:"essence / nature",pos:"noun",    example:"问题的本质是什么？",   exampleMeaning:"What is the essence of the problem?" },
    { char:"矛盾", pinyin:"máodùn",    tone:2, meaning:"contradiction",   pos:"noun",    example:"事物都有矛盾。",       exampleMeaning:"Everything has contradictions." },
    { char:"规律", pinyin:"guīlǜ",     tone:1, meaning:"law / regularity",pos:"noun",    example:"事物有它的规律。",     exampleMeaning:"Things have their own laws." },
    { char:"现象", pinyin:"xiànxiàng", tone:4, meaning:"phenomenon",      pos:"noun",    example:"这是个有趣的现象。",   exampleMeaning:"This is an interesting phenomenon." },
    { char:"趋势", pinyin:"qūshì",     tone:1, meaning:"trend",           pos:"noun",    example:"这是一个全球趋势。",   exampleMeaning:"This is a global trend." },
    { char:"核心", pinyin:"héxīn",     tone:2, meaning:"core / kernel",   pos:"noun",    example:"这是核心问题。",       exampleMeaning:"This is the core issue." },
    { char:"层面", pinyin:"céngmiàn",  tone:2, meaning:"level / dimension",pos:"noun",   example:"从不同层面来看。",     exampleMeaning:"Looking from different dimensions." },
    { char:"背景", pinyin:"bèijǐng",   tone:4, meaning:"background",      pos:"noun",    example:"了解历史背景很重要。",  exampleMeaning:"Understanding historical background is important." },
    { char:"传统", pinyin:"chuántǒng", tone:2, meaning:"tradition",       pos:"noun",    example:"我们要继承传统文化。",  exampleMeaning:"We should inherit traditional culture." },
    { char:"创新", pinyin:"chuàngxīn", tone:4, meaning:"innovation",      pos:"verb",    example:"公司不断创新。",       exampleMeaning:"The company continuously innovates." },
    { char:"可持续",pinyin:"kě chíxù", tone:3, meaning:"sustainable",     pos:"adj",     example:"可持续发展很重要。",   exampleMeaning:"Sustainable development is important." },
    { char:"全球化",pinyin:"quánqiúhuà",tone:2,meaning:"globalization",   pos:"noun",    example:"全球化带来机遇和挑战。",exampleMeaning:"Globalization brings opportunities and challenges." },
    { char:"多元化",pinyin:"duōyuánhuà",tone:1,meaning:"diversification", pos:"noun",    example:"社会越来越多元化。",   exampleMeaning:"Society is increasingly diversified." },
    { char:"批判性",pinyin:"pīpànxìng",tone:1,meaning:"critical (thinking)",pos:"adj",   example:"要有批判性思维。",     exampleMeaning:"One must have critical thinking." },
    { char:"客观",  pinyin:"kèguān",   tone:4, meaning:"objective",       pos:"adj",     example:"要客观地分析问题。",   exampleMeaning:"We must analyze problems objectively." },
    { char:"主观",  pinyin:"zhǔguān",  tone:3, meaning:"subjective",      pos:"adj",     example:"不要太主观。",         exampleMeaning:"Don't be too subjective." },
    { char:"宏观",  pinyin:"hóngguān", tone:2, meaning:"macro / big picture",pos:"adj",  example:"从宏观角度看。",       exampleMeaning:"Looking from a macro perspective." },
    { char:"微观",  pinyin:"wēiguān",  tone:1, meaning:"micro",           pos:"adj",     example:"微观分析也很重要。",   exampleMeaning:"Micro analysis is also important." },
    { char:"辐射",  pinyin:"fúshè",    tone:2, meaning:"radiation / to radiate",pos:"verb",example:"手机辐射对人有影响吗？",exampleMeaning:"Does phone radiation affect people?" },
    { char:"探索",  pinyin:"tànsuǒ",   tone:4, meaning:"to explore",      pos:"verb",    example:"人类不断探索宇宙。",   exampleMeaning:"Humans continuously explore the universe." },
    { char:"诠释",  pinyin:"quánshì",  tone:2, meaning:"to interpret",    pos:"verb",    example:"他对这首诗有独特的诠释。",exampleMeaning:"He has a unique interpretation of this poem." },
    { char:"融合",  pinyin:"rónghé",   tone:2, meaning:"to merge / integrate",pos:"verb", example:"东西方文化融合。",     exampleMeaning:"Eastern and Western cultures are merging." },
    { char:"渗透",  pinyin:"shèntòu",  tone:4, meaning:"to permeate",     pos:"verb",    example:"技术渗透到生活各处。",  exampleMeaning:"Technology permeates all aspects of life." },
  ],

};
